### ISSUE TITLE
version notice and loading error

### ISSUE THREAD

**Issue by LaszloA** [healiseu/dbapiProject#1]
It is worth to notice that this package works only with Mathematica 10.2 and above. This is because it uses the RawJSON format introduced by this version. New users should be warned about this.

When loading the package received the following errors:
Cannot open DBAPI`FreebaseAPI`. >>
Cannot open DBAPI`OrientR3S3'. >>

Simply, don't know why is that. Worth to mention that the simple tests suggested by the author are working, it seems these errors has no effects (at least for what I tested till now). I am using Mathematica for Windows 64bit 10.3.1.0. Thank you for your attention.

**Comment by healiseu** [comment]
@LaszloA thank you for your feedback. You may ignore these errors, I forgot to edit the init.m file. Find this file under `DBAPI/Kernel` of the project and remove 

``` JAVASCRIPT
Get[ "DBAPI`FreebaseAPI`"];
Get[ "DBAPI`OrientR3S3`"];

You may also use

DBAPI`OrientDB`
```

to load the **ONLY two** packages that are included in the `DBAPI` context. See also ODBapi documentation pages with Mathematica Help system.

**Comment by LaszloA** [comment]
Thank you, it works. Could I understand that these are coming modules?

**Comment by healiseu** [comment]
Yes ;-)

**Comment by LaszloA** [comment]
Nice! Thank you very much for your work, wish you SUCCESS!
